variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

stages:
  - npm-build

npm-build:
  stage: npm-build
  image: node:23.7-alpine
  script:
    - echo "Start building Next App"
    - npm install
    #    - npm install --legacy-peer-deps
    #    - npm build
    - npm run build
    - echo "Build Next App successfully!"
