/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/catalogues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all catalogues */
        get: operations["list_catalogues_v1_catalogues_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/catalogues/{catalogue_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Single catalogue detail */
        get: operations["get_catalogue_v1_catalogues__catalogue_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/catalogues/{catalogue_id}/facets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Facet exposure status for a catalogue */
        get: operations["catalogue_facets_v1_catalogues__catalogue_id__facets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/catalogues/{catalogue_id}/vocabularies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Vocabularies used by a catalogue */
        get: operations["catalogue_vocabularies_v1_catalogues__catalogue_id__vocabularies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/catalogues/{catalogue_id}/facet-coverage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Compact six-cell facet coverage for the Overview cards */
        get: operations["catalogue_facet_coverage_v1_catalogues__catalogue_id__facet_coverage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/catalogues/{catalogue_id}/provenance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lineage information for a catalogue */
        get: operations["catalogue_provenance_v1_catalogues__catalogue_id__provenance_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/facets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the six pivot facets */
        get: operations["list_facets_v1_facets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/facets/{facet}/values": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Facet values with counts and timestamps */
        get: operations["facet_values_v1_facets__facet__values_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/facets/{facet}/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Transversal side-by-side comparison across catalogues */
        get: operations["facet_compare_v1_facets__facet__compare_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/facets/{facet}/timeseries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Evolution of a facet over time */
        get: operations["facet_timeseries_v1_facets__facet__timeseries_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/vocabularies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Vocabulary inventory */
        get: operations["list_vocabularies_v1_vocabularies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/vocabularies/{vocabulary_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Vocabulary detail */
        get: operations["get_vocabulary_v1_vocabularies__vocabulary_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/vocabularies/{vocabulary_id}/concepts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Paginated concepts of a vocabulary */
        get: operations["vocabulary_concepts_v1_vocabularies__vocabulary_id__concepts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/mappings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Declared cross-vocabulary mappings */
        get: operations["list_mappings_v1_mappings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/mappings/overlap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Transversal overlap between two vocabularies */
        get: operations["vocabulary_overlap_v1_mappings_overlap_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/snapshots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List snapshots */
        get: operations["list_snapshots_v1_snapshots_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/snapshots/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current snapshot metadata */
        get: operations["latest_snapshot_v1_snapshots_latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Latest harvest activity per catalogue for the Overview panel */
        get: operations["activity_v1_activity_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Application name and version */
        get: operations["version_version_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Catalogue */
        Catalogue: {
            /**
             * Id
             * @description Stable identifier, lowercase and hyphen-separated.
             */
            id: string;
            /**
             * Name
             * @description Display name of the catalogue.
             */
            name: string;
            /**
             * Domain
             * @description Primary domain covered by the catalogue.
             */
            domain: string;
            /**
             * Url
             * Format: uri
             * @description Public entry point of the catalogue.
             */
            url: string;
            /**
             * Total Resources
             * @description Total resources described by the catalogue.
             */
            total_resources: number;
            /**
             * Vocabularies Count
             * @description Number of vocabularies used by the catalogue.
             */
            vocabularies_count: number;
            /**
             * Vocabularies Mapped
             * @description Number of used vocabularies with declared cross-mappings.
             */
            vocabularies_mapped: number;
            /**
             * Licence
             * @description Licence under which the catalogue exposes its metadata.
             */
            licence: string;
            /**
             * Last Harvest At
             * Format: date-time
             * @description Timestamp of the last successful harvest.
             */
            last_harvest_at: string;
            /** @description Status of the most recent harvest. */
            harvest_status: components["schemas"]["HarvestStatus"];
            /**
             * Languages Summary
             * @description Short summary of the languages present in the catalogue.
             */
            languages_summary?: string | null;
        };
        /** Concept */
        Concept: {
            /**
             * Uri
             * Format: uri
             * @description Stable URI identifying the concept.
             */
            uri: string;
            /**
             * Pref Label
             * @description Preferred label of the concept.
             */
            pref_label: string;
            /**
             * Scheme
             * @description Concept scheme the term belongs to.
             */
            scheme: string;
            /**
             * Vocabulary Id
             * @description Identifier of the owning vocabulary.
             */
            vocabulary_id: string;
        };
        /** ConceptRef */
        ConceptRef: {
            /**
             * Uri
             * Format: uri
             * @description Stable URI identifying the concept.
             */
            uri: string;
            /**
             * Pref Label
             * @description Preferred label of the concept.
             */
            pref_label: string;
            /**
             * Scheme
             * @description Concept scheme or authority the term belongs to.
             */
            scheme: string;
        };
        /** ErrorResponse */
        ErrorResponse: {
            /**
             * Detail
             * @description Human-readable error message.
             */
            detail: string;
            /**
             * Code
             * @description Machine-readable error code.
             */
            code: string;
        };
        /** FacetComparison */
        FacetComparison: {
            /** @description Pivot facet being compared. */
            facet: components["schemas"]["PivotFacet"];
            /**
             * Catalogues
             * @description Catalogues included in the comparison.
             */
            catalogues: string[];
            /**
             * Snapshot Timestamp
             * Format: date-time
             * @description Snapshot the comparison is based on.
             */
            snapshot_timestamp: string;
            /**
             * Values
             * @description One row per distinct facet value.
             */
            values: components["schemas"]["FacetComparisonRow"][];
        };
        /** FacetComparisonRow */
        FacetComparisonRow: {
            /**
             * Value
             * @description Facet value compared across catalogues.
             */
            value: string;
            /**
             * Counts
             * @description Per-catalogue count, null means the facet is a gap for that catalogue.
             */
            counts: {
                [key: string]: number | null;
            };
        };
        /** FacetExposure */
        FacetExposure: {
            /**
             * Catalogue Id
             * @description Catalogue the exposure refers to.
             */
            catalogue_id: string;
            /** @description Pivot facet being described. */
            facet: components["schemas"]["PivotFacet"];
            /** @description How the catalogue exposes this facet. */
            status: components["schemas"]["FacetExposureStatus"];
            /**
             * Reason
             * @description Explanation when the facet is a gap, implicit or partial.
             */
            reason?: string | null;
            /**
             * Values Count
             * @description Number of distinct values, null when not exposed.
             */
            values_count?: number | null;
            /**
             * Top Value
             * @description Most frequent value, null when not exposed.
             */
            top_value?: string | null;
            /**
             * Top Value Count
             * @description Count of the most frequent value.
             */
            top_value_count?: number | null;
            /**
             * Total Count
             * @description Sum of counts across all values of the facet.
             */
            total_count?: number | null;
        };
        /**
         * FacetExposureStatus
         * @enum {string}
         */
        FacetExposureStatus: "exposed" | "partial" | "implicit" | "gap";
        /** FacetTimeseriesPoint */
        FacetTimeseriesPoint: {
            /**
             * Catalogue Id
             * @description Catalogue the point belongs to.
             */
            catalogue_id: string;
            /** @description Pivot facet the point belongs to. */
            facet: components["schemas"]["PivotFacet"];
            /**
             * Timestamp
             * Format: date-time
             * @description Timestamp of the snapshot.
             */
            timestamp: string;
            /**
             * Total Count
             * @description Total count for the facet at this timestamp.
             */
            total_count: number;
        };
        /** FacetValue */
        FacetValue: {
            /**
             * Catalogue Id
             * @description Catalogue the value belongs to.
             */
            catalogue_id: string;
            /** @description Pivot facet the value belongs to. */
            facet: components["schemas"]["PivotFacet"];
            /**
             * Value
             * @description Facet value label.
             */
            value: string;
            /**
             * Count
             * @description Number of resources carrying this value.
             */
            count: number;
            /**
             * Timestamp
             * Format: date-time
             * @description Snapshot timestamp of the count.
             */
            timestamp: string;
            /** @description Controlled vocabulary term backing the value, if any. */
            vocabulary_term?: components["schemas"]["ConceptRef"] | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HarvestStatus
         * @enum {string}
         */
        HarvestStatus: "live" | "degraded" | "unreachable";
        /** Mapping */
        Mapping: {
            /** @description Concept the mapping starts from. */
            source_concept: components["schemas"]["ConceptRef"];
            /** @description Concept the mapping points to. */
            target_concept: components["schemas"]["ConceptRef"];
            /** @description SKOS mapping relation between the concepts. */
            relation: components["schemas"]["MappingRelation"];
            /**
             * Authority
             * @description Source that declared the mapping.
             */
            authority: string;
        };
        /**
         * MappingRelation
         * @enum {string}
         */
        MappingRelation: "exactMatch" | "closeMatch" | "broadMatch" | "narrowMatch" | "relatedMatch";
        /** PaginatedConcepts */
        PaginatedConcepts: {
            /** @description Pagination window over the concept list. */
            pagination: components["schemas"]["Pagination"];
            /**
             * Items
             * @description Concepts in the requested window.
             */
            items: components["schemas"]["Concept"][];
        };
        /** Pagination */
        Pagination: {
            /**
             * Offset
             * @description Index of the first returned item.
             */
            offset: number;
            /**
             * Limit
             * @description Maximum number of items returned.
             */
            limit: number;
            /**
             * Total
             * @description Total number of items available.
             */
            total: number;
        };
        /**
         * PivotFacet
         * @enum {string}
         */
        PivotFacet: "resource-type" | "format" | "discipline" | "source" | "source-2" | "subjects";
        /** Snapshot */
        Snapshot: {
            /**
             * Id
             * @description Stable identifier of the snapshot.
             */
            id: string;
            /**
             * Taken At
             * Format: date-time
             * @description Timestamp the snapshot was taken.
             */
            taken_at: string;
            /**
             * Catalogues Included
             * @description Catalogue identifiers covered by the snapshot.
             */
            catalogues_included: string[];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** Vocabulary */
        Vocabulary: {
            /**
             * Id
             * @description Stable identifier of the vocabulary.
             */
            id: string;
            /**
             * Name
             * @description Display name of the vocabulary.
             */
            name: string;
            /**
             * Authority
             * @description Organisation maintaining the vocabulary.
             */
            authority: string;
            /**
             * Uri
             * @description Canonical URI of the vocabulary.
             */
            uri?: string | null;
            /**
             * Concepts Count
             * @description Number of concepts in the vocabulary.
             */
            concepts_count: number;
            /**
             * Used For Facets
             * @description Pivot facets this vocabulary provides terms for.
             */
            used_for_facets: components["schemas"]["PivotFacet"][];
            /**
             * Used By Catalogues
             * @description Catalogue identifiers using this vocabulary.
             */
            used_by_catalogues: string[];
        };
        /** VocabularyOverlap */
        VocabularyOverlap: {
            /**
             * Vocab A
             * @description First vocabulary identifier.
             */
            vocab_a: string;
            /**
             * Vocab B
             * @description Second vocabulary identifier.
             */
            vocab_b: string;
            /**
             * Shared Concepts
             * @description Number of concepts mapped between the two.
             */
            shared_concepts: number;
            /**
             * Total A
             * @description Total concepts in the first vocabulary.
             */
            total_a: number;
            /**
             * Total B
             * @description Total concepts in the second vocabulary.
             */
            total_b: number;
            /**
             * Mapping Relations
             * @description Count of shared concepts per mapping relation.
             */
            mapping_relations: {
                [key: string]: number;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_catalogues_v1_catalogues_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Catalogue"][];
                };
            };
        };
    };
    get_catalogue_v1_catalogues__catalogue_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                catalogue_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Catalogue"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    catalogue_facets_v1_catalogues__catalogue_id__facets_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                catalogue_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FacetExposure"][];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    catalogue_vocabularies_v1_catalogues__catalogue_id__vocabularies_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                catalogue_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Vocabulary"][];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    catalogue_facet_coverage_v1_catalogues__catalogue_id__facet_coverage_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                catalogue_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: components["schemas"]["FacetExposureStatus"];
                    };
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    catalogue_provenance_v1_catalogues__catalogue_id__provenance_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                catalogue_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_facets_v1_facets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    facet_values_v1_facets__facet__values_get: {
        parameters: {
            query?: {
                /** @description Comma-separated catalogue identifiers to restrict the result. */
                catalogues?: string | null;
                from?: string | null;
                to?: string | null;
            };
            header?: never;
            path: {
                facet: components["schemas"]["PivotFacet"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FacetValue"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    facet_compare_v1_facets__facet__compare_get: {
        parameters: {
            query?: {
                /** @description Comma-separated catalogue identifiers to restrict the result. */
                catalogues?: string | null;
            };
            header?: never;
            path: {
                facet: components["schemas"]["PivotFacet"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FacetComparison"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    facet_timeseries_v1_facets__facet__timeseries_get: {
        parameters: {
            query?: {
                /** @description Comma-separated catalogue identifiers to restrict the result. */
                catalogues?: string | null;
                from?: string | null;
                to?: string | null;
            };
            header?: never;
            path: {
                facet: components["schemas"]["PivotFacet"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FacetTimeseriesPoint"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_vocabularies_v1_vocabularies_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Vocabulary"][];
                };
            };
        };
    };
    get_vocabulary_v1_vocabularies__vocabulary_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vocabulary_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Vocabulary"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    vocabulary_concepts_v1_vocabularies__vocabulary_id__concepts_get: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
            };
            header?: never;
            path: {
                vocabulary_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedConcepts"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_mappings_v1_mappings_get: {
        parameters: {
            query?: {
                vocab_a?: string | null;
                vocab_b?: string | null;
                relation?: components["schemas"]["MappingRelation"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Mapping"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    vocabulary_overlap_v1_mappings_overlap_get: {
        parameters: {
            query: {
                vocab_a: string;
                vocab_b: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VocabularyOverlap"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_snapshots_v1_snapshots_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Snapshot"][];
                };
            };
        };
    };
    latest_snapshot_v1_snapshots_latest_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Snapshot"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    activity_v1_activity_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    version_version_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
