/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/catalogues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all catalogues */
        get: operations["list_catalogues_v1_catalogues_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/catalogues/{catalogue_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Single catalogue detail */
        get: operations["get_catalogue_v1_catalogues__catalogue_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/catalogues/{catalogue_id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Catalogue versions */
        get: operations["catalogue_versions_v1_catalogues__catalogue_id__versions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/catalogues/{catalogue_id}/versions/last": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Last catalogue version */
        get: operations["catalogue_version_last_v1_catalogues__catalogue_id__versions_last_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/catalogues/{catalogue_id}/versions/{version_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Single catalogue version */
        get: operations["catalogue_version_by_id_v1_catalogues__catalogue_id__versions__version_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/catalogues/{catalogue_id}/versions/last/facet_values": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Facet values */
        get: operations["catalogue_last_facet_values_v1_catalogues__catalogue_id__versions_last_facet_values_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/facets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the facets */
        get: operations["list_facets_v1_facets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/facets/values": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Facet values */
        get: operations["facet_values_v1_facets_values_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/vocabularies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Vocabulary inventory */
        get: operations["list_vocabularies_v1_vocabularies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/vocabularies/{vocabulary_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Vocabulary detail */
        get: operations["get_vocabulary_v1_vocabularies__vocabulary_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Application name and version */
        get: operations["version_version_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/harvest/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Scheduled tasks information */
        get: operations["get_tasks_harvest_tasks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/harvest/tasks/{task_id}/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pause a scheduled task */
        post: operations["pause_tasks_harvest_tasks__task_id__pause_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/harvest/tasks/{task_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume a scheduled task */
        post: operations["resume_tasks_harvest_tasks__task_id__resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/harvest/{catalogue_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Harvest a specific catalogue or all */
        post: operations["post_harvest_harvest__catalogue_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/backup/page": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Backup page redirection */
        get: operations["get_page_backup_page_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/backup/last-update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Last backup timestamp */
        get: operations["get_last_update_backup_last_update_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/backup/last-update-info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Last backup information */
        get: operations["get_last_update_info_backup_last_update_info_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/backup/create-backup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a new backup manually */
        post: operations["post_create_backup_backup_create_backup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/export/ao-cat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export data to AO-Cat format */
        get: operations["get_export_ao_cat_export_ao_cat_get"];
        put?: never;
        /** Update AO-Cat: recompute and write ttl */
        post: operations["post_update_ao_cat_export_ao_cat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BackupInfo */
        BackupInfo: {
            /** Last Update */
            last_update: string;
            /**
             * Data Files
             * @default []
             */
            data_files: components["schemas"]["DataFile"][];
        };
        /** BackupLastUpdate */
        BackupLastUpdate: {
            /** Last Update */
            last_update: string;
        };
        /** Catalogue */
        Catalogue: {
            /**
             * Id
             * @description Stable identifier, lowercase and hyphen-separated.
             */
            id: string;
            /**
             * Name
             * @description Display name of the catalogue.
             */
            name: string;
            /**
             * Domain
             * @description Primary domain covered by the catalogue.
             */
            domain: string;
            /**
             * Url
             * Format: uri
             * @description Public entry point of the catalogue.
             */
            url: string;
            /**
             * Licence
             * @description Licence under which the catalogue exposes its metadata.
             */
            licence: string;
            /**
             * Languages Summary
             * @description Short summary of the languages present in the catalogue.
             */
            languages_summary: string;
        };
        /** CatalogueVersion */
        CatalogueVersion: {
            /**
             * Catalogue Id
             * @description Stable identifier, lowercase and hyphen-separated.
             */
            catalogue_id: string;
            /**
             * Version Id
             * Format: uuid
             * @description Version identifier.
             */
            version_id: string;
            /**
             * Total Resources
             * @description Total resources described by the catalogue.
             * @default 0
             */
            total_resources: number;
            /**
             * Harvest At
             * Format: date-time
             * @description Timestamp of the harvest.
             */
            harvest_at: string;
            /**
             * @description Status of harvest.
             * @default success
             */
            harvest_status: components["schemas"]["HarvestStatus"];
            /**
             * Harvest Error
             * @description Reason of harvest error.
             */
            harvest_error?: string | null;
            /**
             * Vocabularies
             * @description Used vocabularies.
             * @default []
             */
            vocabularies: string[];
            /**
             * Facet Exposures
             * @description Facet exposures.
             * @default []
             */
            facet_exposures: components["schemas"]["FacetExposure"][];
        };
        /**
         * Collection
         * @enum {string}
         */
        Collection: "catalogues" | "catalogues_versions" | "facet_values" | "vocabularies";
        /** DataFile */
        DataFile: {
            collection: components["schemas"]["Collection"];
            /** Filename */
            filename: string;
            /** Size */
            size: number;
            /** Catalogue */
            catalogue?: string | null;
            /** Version */
            version?: string | null;
            /** Harvest At */
            harvest_at?: string | null;
            /** Size Human */
            readonly size_human: string;
        };
        /** ErrorResponse */
        ErrorResponse: {
            /**
             * Detail
             * @description Human-readable error message.
             */
            detail: string | null;
            /**
             * Code
             * @description Machine-readable error code.
             */
            code: string;
        };
        /** FacetExposure */
        FacetExposure: {
            /** @description The facet identifier. */
            facet: components["schemas"]["FacetId"];
            /**
             * @description How the catalogue exposes this facet.
             * @default exposed
             */
            status: components["schemas"]["FacetExposureStatus"];
            /**
             * Reason
             * @description Explanation when the facet is a gap, or implicit.
             */
            reason?: string | null;
            /**
             * Values Count
             * @description Number of distinct values, null when not exposed.
             */
            values_count?: number | null;
            /**
             * Total Count
             * @description Sum of counts across all values of the facet.
             */
            total_count?: number | null;
        };
        /**
         * FacetExposureStatus
         * @enum {string}
         */
        FacetExposureStatus: "exposed" | "implicit" | "gap";
        /**
         * FacetId
         * @enum {string}
         */
        FacetId: "resource-type" | "format" | "discipline" | "source" | "source-2" | "subjects";
        /** FacetValue */
        FacetValue: {
            /**
             * Catalogue Id
             * @description Catalogue the value belongs to.
             */
            catalogue_id: string;
            /**
             * Version Id
             * Format: uuid
             * @description Catalogue version the value belongs to.
             */
            version_id: string;
            /** @description Facet the value belongs to. */
            facet: components["schemas"]["FacetId"];
            /**
             * Value
             * @description Facet value label.
             */
            value: string;
            /**
             * Count
             * @description Number of resources carrying this value.
             */
            count: number;
        };
        /**
         * FacetValuesSort
         * @enum {string}
         */
        FacetValuesSort: "facet" | "value" | "count";
        /**
         * FacetValuesSortDirection
         * @enum {string}
         */
        FacetValuesSortDirection: "asc" | "desc";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HarvestStatus
         * @enum {string}
         */
        HarvestStatus: "success" | "error";
        /** Health */
        Health: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "error";
        };
        /** Page[FacetValue] */
        Page_FacetValue_: {
            /** Items */
            items: components["schemas"]["FacetValue"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Size */
            size: number;
            /** Pages */
            pages: number;
        };
        /** Task */
        Task: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Next Run Time */
            next_run_time?: string | null;
            /** Trigger */
            trigger: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** Version */
        Version: {
            /** Name */
            name: string;
            /** Version */
            version: string;
        };
        /** Vocabulary */
        Vocabulary: {
            /**
             * Id
             * @description Stable identifier of the vocabulary.
             */
            id: string;
            /**
             * Name
             * @description Display name of the vocabulary.
             */
            name: string;
            /**
             * Authority
             * @description Organisation maintaining the vocabulary.
             */
            authority: string;
            /**
             * Uri
             * @description Canonical URI of the vocabulary.
             */
            uri?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_catalogues_v1_catalogues_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Catalogue"][];
                };
            };
        };
    };
    get_catalogue_v1_catalogues__catalogue_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                catalogue_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Catalogue"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    catalogue_versions_v1_catalogues__catalogue_id__versions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                catalogue_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogueVersion"][];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    catalogue_version_last_v1_catalogues__catalogue_id__versions_last_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                catalogue_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogueVersion"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    catalogue_version_by_id_v1_catalogues__catalogue_id__versions__version_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                catalogue_id: string;
                version_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogueVersion"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    catalogue_last_facet_values_v1_catalogues__catalogue_id__versions_last_facet_values_get: {
        parameters: {
            query?: {
                sort?: components["schemas"]["FacetValuesSort"] | null;
                direction?: components["schemas"]["FacetValuesSortDirection"] | null;
                /** @description Page number */
                page?: number;
                /** @description Page size */
                size?: number;
            };
            header?: never;
            path: {
                catalogue_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_FacetValue_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_facets_v1_facets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FacetId"][];
                };
            };
        };
    };
    facet_values_v1_facets_values_get: {
        parameters: {
            query?: {
                /** @description Comma-separated facet identifiers to restrict the result. */
                facets?: string | null;
                /** @description Comma-separated catalogue identifiers to restrict the result. */
                catalogues?: string | null;
                sort?: components["schemas"]["FacetValuesSort"] | null;
                direction?: components["schemas"]["FacetValuesSortDirection"] | null;
                /** @description Page number */
                page?: number;
                /** @description Page size */
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_FacetValue_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_vocabularies_v1_vocabularies_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Vocabulary"][];
                };
            };
        };
    };
    get_vocabulary_v1_vocabularies__vocabulary_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vocabulary_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Vocabulary"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    version_version_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Version"];
                };
            };
        };
    };
    get_tasks_harvest_tasks_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"][];
                };
            };
        };
    };
    pause_tasks_harvest_tasks__task_id__pause_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_tasks_harvest_tasks__task_id__resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_harvest_harvest__catalogue_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                catalogue_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request Timeout */
            408: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_page_backup_page_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            301: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_last_update_backup_last_update_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BackupLastUpdate"];
                };
            };
        };
    };
    get_last_update_info_backup_last_update_info_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BackupInfo"];
                };
            };
        };
    };
    post_create_backup_backup_create_backup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BackupInfo"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_export_ao_cat_export_ao_cat_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    post_update_ao_cat_export_ao_cat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
